---
- hosts: localhost
  gather_facts: false

  collections:
    - netapp.ontap
  vars:
    netapp_hostname: "cluster1"
    netapp_username: "admin"
    netapp_password: "PaSSw@ord"

    # No modifications below this point should be required for validation. 
    opt_info_gather_subset_01: "aggregate_info"
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ netapp_https | default(true) }}"
      port: "{{ netapp_port | default(omit) }}"
      validate_certs: "{{ validate_certs | default(false) }}"

  tasks:
  - name: Running command na_ontap_info
    na_ontap_info:
      <<: *login
      gather_subset: '{{ opt_info_gather_subset_01 | default(omit) }}'
    register: results

  - name: Debug results
    debug:
      var: results.ontap_info.aggregate_info|list

